services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: planing
      MYSQL_USER: planing
      MYSQL_PASSWORD: planing
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

